/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myproject;

import myproject.console.impl.Console;
import myproject.console.IConsole;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void input_int_test(){
        IConsole console = new Console();
        int number = console.readInteger("Enter number for x: ");
    }
}
